version: "3.8"
services:
  web:
    build: .
    image: my-flask-app:local
    ports:
      - "8080:8080"
    environment:
      - FLASK_ENV=production
    depends_on:
      - db
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: realworld
    ports:
      - "5432:5432"
